import type { CSSProperties } from "react";

export const styles: Record<string, CSSProperties> = {
 btnDanger: {
    background: "#FEF2F2",
    color: "#E53E3E",
    border: "1.5px solid #FED7D7",
    borderRadius: "8px",
    padding: "7px 12px",
    fontSize: "12px",
    fontWeight: 600,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    gap: "5px",
  },

  
  // Modal
  overlay: {
    position: "fixed" as const,
    inset: 0,
    background: "rgba(15,22,36,0.45)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 1000,
    backdropFilter: "blur(2px)",
  },
  modal: {
    background: "#fff",
    borderRadius: "18px",
    padding: "32px",
    width: "100%",
    maxWidth: "480px",
    boxShadow: "0 20px 60px rgba(15,22,36,0.2)",
    position: "relative" as const,
  },
  modalTitle: {
    fontSize: "18px",
    fontWeight: 700,
    color: "#1E2A3B",
    marginBottom: "4px",
  },
  modalSubtitle: {
    fontSize: "13px",
    color: "#8A9BB0",
    marginBottom: "24px",
  },
  formGroup: {
    marginBottom: "18px",
  },
  label: {
    display: "block",
    fontSize: "12px",
    fontWeight: 700,
    color: "#4A5568",
    marginBottom: "6px",
    textTransform: "uppercase" as const,
    letterSpacing: "0.05em",
  },
  input: {
    width: "100%",
    padding: "10px 14px",
    border: "1.5px solid #E2E8F0",
    borderRadius: "10px",
    fontSize: "14px",
    color: "#1E2A3B",
    outline: "none",
    boxSizing: "border-box" as const,
    transition: "border-color 0.15s",
    background: "#FAFBFF",
  },
  select: {
    width: "100%",
    padding: "10px 14px",
    border: "1.5px solid #E2E8F0",
    borderRadius: "10px",
    fontSize: "14px",
    color: "#1E2A3B",
    outline: "none",
    boxSizing: "border-box" as const,
    background: "#FAFBFF",
    appearance: "none" as const,
  },
  row2: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "14px",
  },
  modalFooter: {
    display: "flex",
    justifyContent: "flex-end",
    gap: "10px",
    marginTop: "28px",
  },
  btnCancel: {
    background: "#F4F6FB",
    color: "#6B7FA3",
    border: "none",
    borderRadius: "10px",
    padding: "10px 20px",
    fontSize: "13px",
    fontWeight: 600,
    cursor: "pointer",
  },
  btnSave: {
    background: "linear-gradient(135deg, #5B6BDF 0%, #4A5AC8 100%)",
    color: "#fff",
    border: "none",
    borderRadius: "10px",
    padding: "10px 24px",
    fontSize: "13px",
    fontWeight: 600,
    cursor: "pointer",
    boxShadow: "0 2px 8px rgba(91,107,223,0.3)",
  },
  closeBtn: {
    position: "absolute" as const,
    top: "18px",
    right: "18px",
    background: "#F4F6FB",
    border: "none",
    borderRadius: "8px",
    padding: "6px",
    cursor: "pointer",
    display: "flex",
    color: "#6B7FA3",
  },

  // ── Layout ──
  pageWrapper: {
    display: "flex",
    flexDirection: "column" as const,
    height: "100%",
    gap: 0,
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 20,
    flexShrink: 0,
    flexWrap: "wrap" as const,
    gap: 12,
  },
  pageTitle: {
    fontSize: 22,
    fontWeight: 700,
    color: "#111827",
    margin: "0 0 2px",
  },
  pageSubtitle: {
    color: "#9ca3af",
    fontSize: 13,
    margin: 0,
  },
  btnBack: {
    background: "none",
    border: "1px solid #e5e7eb",
    borderRadius: 8,
    padding: "8px 16px",
    fontSize: 13,
    fontWeight: 500,
    color: "#374151",
    cursor: "pointer",
  },

  // ── Body ──
  scrollBody: {
    flex: 1,
    minHeight: 0,
    overflowY: "auto" as const,
    display: "flex",
    flexDirection: "column" as const,
    gap: 18,
  },
  tableCard: {
    background: "#fff",
    borderRadius: 14,
    padding: "24px 28px",
    boxShadow: "0 1px 4px rgba(0,0,0,.06)",
    flex: 1,
    minHeight: 0,
    display: "flex",
    flexDirection: "column" as const,
  },
  filterBar: {
    display: "flex",
    gap: 6,
    flexWrap: "wrap" as const,
    marginBottom: 20,
    flexShrink: 0,
  },
  filterBadge: {
    border: "1px solid #e5e7eb",
    borderRadius: 8,
    padding: "6px 14px",
    fontSize: 12,
    fontWeight: 600,
    color: "#3b82f6",
    background: "#eff6ff",
  },
  tableWrapper: {
    flex: 1,
    overflowY: "auto" as const,
    minHeight: 0,
  },
  table: {
    width: "100%",
    borderCollapse: "collapse" as const,
    fontSize: 13,
  },
  tableHeadRow: {
    background: "rgba(228,230,239,0.85)",
  },
  th: {
    padding: "10px 14px",
    textAlign: "left" as const,
    fontWeight: 600,
    color: "#374151",
    whiteSpace: "nowrap" as const,
  },
  tableBodyRow: {
    borderBottom: "1px solid #f3f4f6",
  },
  tdDefault: {
    padding: "12px 14px",
    color: "#6b7280",
  },
  tdNoWrap: {
    padding: "12px 14px",
    color: "#6b7280",
    whiteSpace: "nowrap" as const,
  },
  tdBold: {
    padding: "12px 14px",
    fontWeight: 500,
    color: "#111827",
  },
  tdBadge: {
    padding: "12px 14px",
  },
  tdActions: {
    padding: "12px 14px",
  },
  actionGroup: {
    display: "flex",
    gap: 6,
    alignItems: "center",
  },
  btnEdit: {
    background: "#f59e0b",
    color: "#fff",
    border: "none",
    borderRadius: 6,
    padding: "5px 12px",
    fontSize: 12,
    fontWeight: 600,
    cursor: "pointer",
  },
  btnKirim: {
    background: "#22c55e",
    color: "#fff",
    border: "none",
    borderRadius: 6,
    padding: "5px 12px",
    fontSize: 12,
    fontWeight: 600,
    cursor: "pointer",
  },
  btnView: {
    background: "#3b82f6",
    color: "#fff",
    border: "none",
    borderRadius: 6,
    padding: "5px 12px",
    fontSize: 12,
    fontWeight: 600,
    cursor: "pointer",
  },
  emptyCell: {
    padding: "40px 14px",
    textAlign: "center" as const,
    color: "#9ca3af",
    fontSize: 13,
  },

  // ── Toast ──
  toastContainer: {
    position: "fixed" as const,
    bottom: 24,
    right: 24,
    display: "flex",
    flexDirection: "column" as const,
    gap: 10,
    zIndex: 2000,
  },
  toastCloseBtn: {
    background: "none",
    border: "none",
    cursor: "pointer",
    opacity: 0.6,
    fontSize: 14,
  },
};
// Status badge (warna bergantung value status)
export function statusBadgeStyle(status: string | undefined): import("react").CSSProperties {
  return {
    display: "inline-block",
    padding: "3px 10px",
    borderRadius: 20,
    fontSize: 11,
    fontWeight: 700,
    background: status === "draft" ? "#FEF3C7" : status === "final" ? "#F0FDF4" : "#F3F4F6",
    color: status === "draft" ? "#92400E" : status === "final" ? "#15803D" : "#6B7280",
  };
}

// Toast item (warna bergantung type)
export function toastItemStyle(type: "success" | "error"): import("react").CSSProperties {
  return {
    display: "flex",
    alignItems: "center",
    gap: 10,
    background: type === "success" ? "#F0FDF4" : "#FFF1F2",
    border: `1.5px solid ${type === "success" ? "#4ADE80" : "#FDA4AF"}`,
    color: type === "success" ? "#15803D" : "#9F1239",
    borderRadius: 10,
    padding: "12px 16px",
    fontSize: 13,
    fontWeight: 600,
    boxShadow: "0 4px 16px rgba(0,0,0,0.10)",
    minWidth: 260,
    maxWidth: 360,
  };
}