import type { CSSProperties } from "react";
import { colors } from "../../components/colorstyle";

export const styles: Record<string, CSSProperties> = {
  root: {
    fontFamily: "'DM Sans', 'Segoe UI', sans-serif",
    background: colors.white,
    minHeight: "100vh",
    padding: "32px 28px",
    color: "#1E293B",
    borderRadius: "14px",
    boxShadow: "rgba(30, 42, 59, 0.07) 0px 1px 4px", 
    overflow: "hidden",
    border: "1.5px solid rgb(234, 236, 245)",
  },

  header: {
    marginBottom: "24px",
  },

  title: {
    fontSize: "22px",
    fontWeight: 700,
    color: "#0F172A",
    margin: 0,
  },

  subtitle: {
    fontSize: "13px",
    color: "#64748B",
    margin: "4px 0 0",
  },

  statsRow: {
    display: "flex",
    gap: "12px",
    marginBottom: "20px",
    flexWrap: "wrap" as const,
  },

  statBadge: {
    background: "#fff",
    border: "1px solid #E2E8F0",
    borderRadius: "10px",
    padding: "10px 18px",
    fontSize: "13px",
    fontWeight: 600,
    color: "#334155",
    display: "flex",
    alignItems: "center",
    gap: "8px",
    boxShadow: "0 1px 3px rgba(0,0,0,0.06)",
  },

  toolbar: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "20px",
  },

  btnPrimary: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
    background: "#4F46E5",
    color: "#fff",
    border: "none",
    borderRadius: "8px",
    padding: "9px 16px",
    fontSize: "13px",
    fontWeight: 600,
    cursor: "pointer",
  },

  scheduleGrid: {
    display: "flex",
    gap: "14px",
    overflowX: "auto" as const,
    paddingBottom: "12px",
    alignItems: "flex-start",
  },

  dayColumn: {
    minWidth: "160px",
    flex: "1 1 160px",
  },

  dayHeader: {
    textAlign: "center" as const,
    fontWeight: 700,
    fontSize: "12px",
    letterSpacing: "0.08em",
    textTransform: "uppercase" as const,
    padding: "8px 0 10px",
    color: "#475569",
  },

  kelasNama: {
    fontWeight: 700,
    fontSize: "13px",
    color: "#0F172A",
    marginBottom: "3px",
  },

  kelasMaPel: {
    fontSize: "12px",
    color: "#334155",
    fontWeight: 500,
    marginBottom: "3px",
  },

  kelasJam: {
    fontSize: "11px",
    color: "#64748B",
  },

  kelasActions: {
    display: "flex",
    gap: "4px",
    marginTop: "8px",
  },

  btnEdit: {
    display: "flex",
    alignItems: "center",
    gap: "3px",
    background: "#EFF6FF",
    color: "#2563EB",
    border: "1px solid #BFDBFE",
    borderRadius: "5px",
    padding: "3px 8px",
    fontSize: "11px",
    fontWeight: 600,
    cursor: "pointer",
  },

  btnDanger: {
    display: "flex",
    alignItems: "center",
    gap: "3px",
    background: "#FFF1F2",
    color: "#E11D48",
    border: "1px solid #FECDD3",
    borderRadius: "5px",
    padding: "3px 8px",
    fontSize: "11px",
    fontWeight: 600,
    cursor: "pointer",
  },

  emptyDay: {
    textAlign: "center" as const,
    color: "#CBD5E1",
    fontSize: "12px",
    padding: "20px 0",
    border: "1.5px dashed #E2E8F0",
    borderRadius: "10px",
  },

  overlay: {
    position: "fixed" as const,
    inset: 0,
    background: "rgba(15,23,42,0.45)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 1000,
  },

  modal: {
    background: "#fff",
    borderRadius: "16px",
    padding: "28px 28px 24px",
    width: "100%",
    maxWidth: "420px",
    boxShadow: "0 20px 60px rgba(0,0,0,0.18)",
    position: "relative" as const,
  },

  modalTitle: {
    fontSize: "17px",
    fontWeight: 700,
    color: "#0F172A",
    marginBottom: "4px",
  },

  modalSubtitle: {
    fontSize: "13px",
    color: "#64748B",
    marginBottom: "20px",
  },

  formGroup: { marginBottom: "14px" },
  label: { fontSize: "12px", fontWeight: 600, color: "#475569", display: "block", marginBottom: "5px" },
  input: {
    width: "100%",
    border: "1.5px solid #E2E8F0",
    borderRadius: "8px",
    padding: "9px 12px",
    fontSize: "13px",
    outline: "none",
    boxSizing: "border-box" as const,
    color: "#0F172A",
    backgroundColor: "#FFF",
  },

  modalFooter: {
    display: "flex",
    justifyContent: "flex-end",
    gap: "8px",
    marginTop: "20px",
  },

  btnCancel: {
    background: "#F1F5F9",
    color: "#475569",
    border: "none",
    borderRadius: "8px",
    padding: "9px 16px",
    fontSize: "13px",
    fontWeight: 600,
    cursor: "pointer",
  },

  btnSave: {
    background: "#4F46E5",
    color: "#fff",
    border: "none",
    borderRadius: "8px",
    padding: "9px 18px",
    fontSize: "13px",
    fontWeight: 600,
    cursor: "pointer",
  },

  closeBtn: {
    position: "absolute" as const,
    top: "14px",
    right: "14px",
    background: "none",
    border: "none",
    cursor: "pointer",
    color: "#94A3B8",
    padding: "4px",
  },

  select: {
    width: "100%",
    border: "1.5px solid #E2E8F0",
    borderRadius: "8px",
    padding: "9px 12px",
    fontSize: "13px",
    outline: "none",
    boxSizing: "border-box" as const,
    background: "#fff",
    cursor: "pointer",
    color: "#0F172A",
    appearance: "auto" as const,
  },
  
  btnDetail: {
    display: "flex",
    alignItems: "center",
    gap: "3px",
    background: "#F5F3FF",
    color: "#7C3AED",
    border: "1px solid #DDD6FE",
    borderRadius: "5px",
    padding: "3px 8px",
    fontSize: "11px",
    fontWeight: 600,
    cursor: "pointer",
  },

  toastNotif: {
    position: "fixed",
    bottom: "24px",
    right: "24px",
    display: "flex",
    flexDirection: "column",
    gap: "10px",
    zIndex: 2000,
  },

  bodyToastNotif: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    borderRadius: "10px",
    padding: "12px 16px",
    fontSize: "13px",
    fontWeight: 600,
    boxShadow: "0 4px 16px rgba(0,0,0,0.10)",
    minWidth: "260px",
    maxWidth: "360px",
    animation: "slideIn 0.2s ease",
  },

  btnToast: {
    background: "none",
    border: "none",
    cursor: "pointer",
    color: "inherit",
    opacity: 0.6,
    fontSize: "14px",
    padding: "0 2px",
  }

  // root: {
  //   // background: "#F4F6FB",
  //   minHeight: "100vh",
  //   // padding: "32px",
  //   // color: "#1E2A3B",
  // },
  // header: {
  //   marginBottom: "28px",
  // },
  // breadcrumb: {
  //   fontSize: "12px",
  //   color: "#8A9BB0",
  //   marginBottom: "6px",
  //   letterSpacing: "0.04em",
  //   textTransform: "uppercase" as const,
  // },
  // title: {
  //   margin: 0,
  //   fontSize: 26, 
  //   fontWeight: 800, 
  //   color: "#111827", 
  // },
  // subtitle: {
  //   fontSize: "14px",
  //   color: "#6B7FA3",
  //   marginTop: "4px",
  // },
  // toolbar: {
  //   display: "flex",
  //   justifyContent: "space-between",
  //   alignItems: "center",
  //   marginBottom: "20px",
  //   flexWrap: "wrap" as const,
  //   gap: "12px",
  // },
  // statsRow: {
  //   display: "flex",
  //   gap: "16px",
  //   flexWrap: "wrap" as const,
  //   marginBottom: "24px",
  // },
  // statCard: {
  //   background: "#fff",
  //   borderRadius: "12px",
  //   padding: "16px 24px",
  //   display: "flex",
  //   alignItems: "center",
  //   gap: "14px",
  //   boxShadow: "0 1px 4px rgba(30,42,59,0.07)",
  //   minWidth: "160px",
  // },
  // statIcon: {
  //   width: "40px",
  //   height: "40px",
  //   borderRadius: "10px",
  //   display: "flex",
  //   alignItems: "center",
  //   justifyContent: "center",
  //   background: "#EEF2FF",
  //   color: "#5B6BDF",
  //   fontSize: "18px",
  // },
  // statLabel: { fontSize: "12px", color: "#8A9BB0", fontWeight: 500 },
  // statValue: { fontSize: "22px", fontWeight: 700, color: "#1E2A3B" },
  // btnPrimary: {
  //   background: "linear-gradient(135deg, #5B6BDF 0%, #4A5AC8 100%)",
  //   color: "#fff",
  //   border: "none",
  //   borderRadius: "10px",
  //   padding: "10px 18px",
  //   fontSize: "13px",
  //   fontWeight: 600,
  //   cursor: "pointer",
  //   display: "flex",
  //   alignItems: "center",
  //   gap: "7px",
  //   boxShadow: "0 2px 8px rgba(91,107,223,0.25)",
  //   transition: "opacity 0.15s",
  // },
  // btnSecondary: {
  //   background: "#fff",
  //   color: "#5B6BDF",
  //   border: "1.5px solid #D4D9F5",
  //   borderRadius: "10px",
  //   padding: "9px 16px",
  //   fontSize: "13px",
  //   fontWeight: 600,
  //   cursor: "pointer",
  //   display: "flex",
  //   alignItems: "center",
  //   gap: "7px",
  //   transition: "border-color 0.15s",
  // },
  // btnDanger: {
  //   background: "#FEF2F2",
  //   color: "#E53E3E",
  //   border: "1.5px solid #FED7D7",
  //   borderRadius: "8px",
  //   padding: "7px 12px",
  //   fontSize: "12px",
  //   fontWeight: 600,
  //   cursor: "pointer",
  //   display: "flex",
  //   alignItems: "center",
  //   gap: "5px",
  // },
  // btnEdit: {
  //   background: "#EEF2FF",
  //   color: "#5B6BDF",
  //   border: "1.5px solid #D4D9F5",
  //   borderRadius: "8px",
  //   padding: "7px 12px",
  //   fontSize: "12px",
  //   fontWeight: 600,
  //   cursor: "pointer",
  //   display: "flex",
  //   alignItems: "center",
  //   gap: "5px",
  // },
  // kelasCard: {
  //   background: "#fff",
  //   borderRadius: "14px",
  //   marginBottom: "14px",
  //   boxShadow: "0 1px 4px rgba(30,42,59,0.07)",
  //   overflow: "hidden",
  //   border: "1.5px solid #EAECF5",
  //   transition: "box-shadow 0.2s",
  // },
  // kelasHeader: {
  //   padding: "18px 22px",
  //   display: "flex",
  //   alignItems: "center",
  //   justifyContent: "space-between",
  //   cursor: "pointer",
  //   userSelect: "none" as const,
  // },
  // kelasTitle: {
  //   display: "flex",
  //   alignItems: "center",
  //   gap: "14px",
  // },
  // kelasBadge: {
  //   background: "linear-gradient(135deg, #5B6BDF, #4A5AC8)",
  //   color: "#fff",
  //   borderRadius: "10px",
  //   padding: "8px 16px",
  //   fontSize: "16px",
  //   fontWeight: 700,
  //   letterSpacing: "0.02em",
  //   minWidth: "54px",
  //   textAlign: "center" as const,
  // },
  // kelasMeta: {
  //   display: "flex",
  //   gap: "18px",
  //   alignItems: "center",
  //   flexWrap: "wrap" as const,
  // },
  // metaItem: {
  //   fontSize: "12.5px",
  //   color: "#6B7FA3",
  //   display: "flex",
  //   gap: "4px",
  //   alignItems: "center",
  // },
  // metaLabel: { fontWeight: 600, color: "#1E2A3B" },
  // kelasActions: {
  //   display: "flex",
  //   gap: "8px",
  //   alignItems: "center",
  // },
  // siswaCount: {
  //   background: "#EEF2FF",
  //   color: "#5B6BDF",
  //   borderRadius: "20px",
  //   padding: "3px 12px",
  //   fontSize: "12px",
  //   fontWeight: 700,
  //   display: "flex",
  //   alignItems: "center",
  //   gap: "5px",
  // },
  // siswaTable: {
  //   width: "100%",
  //   borderCollapse: "collapse" as const,
  // },
  // tableWrapper: {
  //   padding: "0 22px 18px",
  //   borderTop: "1px solid #F0F2FA",
  // },
  // th: {
  //   textAlign: "left" as const,
  //   fontSize: "11px",
  //   fontWeight: 700,
  //   color: "#8A9BB0",
  //   textTransform: "uppercase" as const,
  //   letterSpacing: "0.06em",
  //   padding: "12px 10px",
  //   borderBottom: "1px solid #F0F2FA",
  // },
  // td: {
  //   padding: "11px 10px",
  //   fontSize: "13px",
  //   color: "#1E2A3B",
  //   borderBottom: "1px solid #F8F9FD",
  // },
  // addSiswaRow: {
  //   padding: "12px 22px 16px",
  // },
  // // Modal
  // overlay: {
  //   position: "fixed" as const,
  //   inset: 0,
  //   background: "rgba(15,22,36,0.45)",
  //   display: "flex",
  //   alignItems: "center",
  //   justifyContent: "center",
  //   zIndex: 1000,
  //   backdropFilter: "blur(2px)",
  // },
  // modal: {
  //   background: "#fff",
  //   borderRadius: "18px",
  //   padding: "32px",
  //   width: "100%",
  //   maxWidth: "480px",
  //   boxShadow: "0 20px 60px rgba(15,22,36,0.2)",
  //   position: "relative" as const,
  // },
  // modalTitle: {
  //   fontSize: "18px",
  //   fontWeight: 700,
  //   color: "#1E2A3B",
  //   marginBottom: "4px",
  // },
  // modalSubtitle: {
  //   fontSize: "13px",
  //   color: "#8A9BB0",
  //   marginBottom: "24px",
  // },
  // formGroup: {
  //   marginBottom: "18px",
  // },
  // label: {
  //   display: "block",
  //   fontSize: "12px",
  //   fontWeight: 700,
  //   color: "#4A5568",
  //   marginBottom: "6px",
  //   textTransform: "uppercase" as const,
  //   letterSpacing: "0.05em",
  // },
  // input: {
  //   width: "100%",
  //   padding: "10px 14px",
  //   border: "1.5px solid #E2E8F0",
  //   borderRadius: "10px",
  //   fontSize: "14px",
  //   color: "#1E2A3B",
  //   outline: "none",
  //   boxSizing: "border-box" as const,
  //   transition: "border-color 0.15s",
  //   background: "#FAFBFF",
  // },
  // select: {
  //   width: "100%",
  //   padding: "10px 14px",
  //   border: "1.5px solid #E2E8F0",
  //   borderRadius: "10px",
  //   fontSize: "14px",
  //   color: "#1E2A3B",
  //   outline: "none",
  //   boxSizing: "border-box" as const,
  //   background: "#FAFBFF",
  //   appearance: "none" as const,
  // },
  // row2: {
  //   display: "grid",
  //   gridTemplateColumns: "1fr 1fr",
  //   gap: "14px",
  // },
  // modalFooter: {
  //   display: "flex",
  //   justifyContent: "flex-end",
  //   gap: "10px",
  //   marginTop: "28px",
  // },
  // btnCancel: {
  //   background: "#F4F6FB",
  //   color: "#6B7FA3",
  //   border: "none",
  //   borderRadius: "10px",
  //   padding: "10px 20px",
  //   fontSize: "13px",
  //   fontWeight: 600,
  //   cursor: "pointer",
  // },
  // btnSave: {
  //   background: "linear-gradient(135deg, #5B6BDF 0%, #4A5AC8 100%)",
  //   color: "#fff",
  //   border: "none",
  //   borderRadius: "10px",
  //   padding: "10px 24px",
  //   fontSize: "13px",
  //   fontWeight: 600,
  //   cursor: "pointer",
  //   boxShadow: "0 2px 8px rgba(91,107,223,0.3)",
  // },
  // closeBtn: {
  //   position: "absolute" as const,
  //   top: "18px",
  //   right: "18px",
  //   background: "#F4F6FB",
  //   border: "none",
  //   borderRadius: "8px",
  //   padding: "6px",
  //   cursor: "pointer",
  //   display: "flex",
  //   color: "#6B7FA3",
  // },
  // emptyState: {
  //   textAlign: "center" as const,
  //   padding: "28px",
  //   color: "#8A9BB0",
  //   fontSize: "13px",
  // },
  // btnDetail: {
  //   display: "flex",
  //   alignItems: "center",
  //   gap: "3px",
  //   background: "#F5F3FF",
  //   color: "#7C3AED",
  //   border: "1px solid #DDD6FE",
  //   borderRadius: "5px",
  //   padding: "3px 8px",
  //   fontSize: "11px",
  //   fontWeight: 600,
  //   cursor: "pointer",
  // }
};
